### PR TITLE
Add quotes around arguments and escape spaces for raw command

### LINKED ISSUE #292: Job name with spaces causes "Unknown command" error
The `--certificate-authority` command line argument is not quoted when the certificate path contains spaces. Parts of the certificate path are interpreted as oc command.

The job that produced the following output is named `test iam-a-funky-command-from-the-job-name`

The pipeline script is minimal:
```
node('agent1') {
    withEnv(["PATH+OC=${tool 'oc3.7.2'}"]) {
        openshift.withCluster( 'mycluster' ) {
            echo "${openshift.raw( "version" ).out}"
            echo "In project: ${openshift.project()}"
        }
    }
}
```

This output demonstrates the problem:
```
ERROR: raw command [version] returned an error;

{reference={}, err=Error: unknown command "iam-a-funky-command-from-the-job-name/serverca8193261019186119850.crt" for "oc"

Run 'oc --help' for usage.

, verb=, cmd=oc --server=https://obscured-openshift-url --certificate-authority=/home/johndoe/.jenkins/workspace/test iam-a-funky-command-from-the-job-name/serverca8193261019186119850.crt --namespace=dbsearch --token=XXXXX  version , out=, status=1}
```
Plugin version `1.0.32`

Seems related to #257

### PR DESCRIPTION
**Pull request by akram**
Fixes #292 

Add quotes around arguments and escape spaces for raw command

### CODE REVIEW

**Comment by akram** [comment]
/hold

I made a mistake in my test

**Comment by cniweb** [comment]
When will this bug be fixed?

**Comment by cniweb** [comment]
@akram When will it continue here?

**Review by cniweb — APPROVED** [review]
LGTM
/retest

**Comment by cniweb** [comment]
LGTM

**Comment by cniweb** [comment]
@akram When will it continue here?

**Pull request closed without merging**
