### PR TITLE
add some retry on watch

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/devex fyi

this is some more of the "retry" I've been referring to in scrum around the flakes we've been seeing in the pipeline jobs when attempting to access the openshift master via `oc` (the TLS handshake errors for example)

as I attempted to note in the comment around the change, this is intended to be a conservative/simplistic application of retry, where minus message parsing there isn't much to do around distinguishing error types

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by stevekuznetsov** [comment]
@gabemontero @bparees not sure this patch makes any sense. We're adding a retry to the _user_ _provided_ closure that gets run inside of the watch body. Not only does this mean that the `error` pipeline step gets eaten by this logic but also `timeout` will not work on watches. We should either add retry to the low-level `oc` actions or ask the user to do retries in their own code, but not this.

**Comment by gabemontero** [comment]
OK, catching back up ...and I think I saw a PR that may have reverted this to at least some degree.  Saving a tab on this one as I step through my post holiday recovery, and will circle back, reconcile, officially chime in once I'm caught up.

**Comment by gabemontero** [comment]
ok, I caught up to the PR around reverting this, etc.

I'll continue the discussion there.

**Pull request merged**
