### PR TITLE
add param/envvar substitution for freestyle step config values

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-client-plugin/issues/69

@openshift/sig-developer-experience fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by eliu** [comment]
Still not merged?

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
So the extended tests passed, but the ec2 deprovision failed 

will merge manually

**Pull request merged**
