### PR TITLE
Selector does not work with multiple labels

### LINKED ISSUE #30: Selector does not work with multiple labels
When I have 2 BuildConfigs in Openshift like this:

BuildConfig 1 labels:

    ref: master
    app: my-app

BuildConfig 2 labels:

    ref: master
    app: my-second-app

I expect 
```
def buildConfigSelector = openshift.selector('bc', [ref: 'master', app: 'my-third-app'])
if (buildConfigSelector.count() > 0) {
 sh 'more than 0'
}
else {
 sh 'no more than 0'
}
```

to print `no more than 0`. But currently it selects either BuildConfig 1 or BuildConfig 2. I can verify this using

```
def result = buildConfigSelector.describe()
sh "echo $result"
```

Describe prints BuildConfig 1 or BuildConfig 2.

### PR DESCRIPTION
**Pull request by tanskann**
Fixes #30 

Correct syntax is this:

```
oc get -l label1=label1value,label2=label2value
```

And not

```
oc get -l label1=label1value -l label2=label2value
```

### CODE REVIEW

**Comment by bparees** [comment]
are you seeing an error?  the multiple -l syntax works for me:
```
$ oc get pods -l app=ruby-helloworld-sample -l deployment=database-1
NAME               READY     STATUS    RESTARTS   AGE
database-1-f0kds   1/1       Running   0          1m
```

```
$ oc get pods -l app=ruby-helloworld-sample -l deployment=database-2
No resources found.
```

I believe the comma separated syntax has been deprecated in most places in preference to passing the argument multiple times, to avoid issues with values that contain commas.

**Comment by tanskann** [comment]
Tried with 1.4.1 and 1.5.1 with same results
```
$ oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server <Redacted>
openshift v3.5.5.15
kubernetes v1.5.2+43a9be4

$ oc get bc -l ref=dsl -l app=helloworld-advanced
NAME                            TYPE      FROM            LATEST
helloworld-advanced-dsl         Source    Git@dsl         26
helloworld-advanced-dsl-new-2   Source    Git@dsl-new-2   7
$ oc describe bc helloworld-advanced-dsl
Name:       helloworld-advanced-dsl
Namespace:  test
Created:    3 weeks ago
Labels:     app=helloworld-advanced
            ref=dsl
Annotations:    <none>
Latest Version: 26

Strategy:       Source
URL:            <Redacted>
Ref:            dsl
Source Secret:      git
From Image:     ImageStreamTag openshift/nodejs:latest
Output to:      DockerImage <Redacted>
Post Commit Hook:   ["/bin/sh", "-ic", "npm test"]
Push Secret:        <Redacted>

Build Run Policy:   Serial
Triggered by:       <none>

Build               Status      Duration    Creation Time
<Redacted>

No events.

$ oc describe bc helloworld-advanced-dsl-new-2
Name:       helloworld-advanced-dsl-new-2
Namespace:  test
Created:    9 days ago
Labels:     app=helloworld-advanced
            ref=dsl-new-2
Annotations:    <none>
Latest Version: 7

Strategy:       Source
URL:            <Redacted>
Ref:            dsl-new-2
Source Secret:      git
From Image:     ImageStreamTag openshift/nodejs:latest
Output to:      DockerImage <Redacted>
Post Commit Hook:   ["/bin/sh", "-ic", "npm test"]
Push Secret:        <Redacted>

Build Run Policy:   Serial
Triggered by:       <none>

Build                   Status      Duration        Creation Time
<Redacted>

No events.

$ oc get bc -l ref=dsl,app=helloworld-advanced
NAME                      TYPE      FROM      LATEST
helloworld-advanced-dsl   Source    Git@dsl   26
```

**Comment by bparees** [comment]
reopening pending the outcome of https://github.com/openshift/origin/issues/14525

**Comment by bparees** [comment]
@gabemontero ptal and see discussion here: https://github.com/openshift/jenkins-client-plugin/issues/30

ultimately the conclusion is that "oc get -l labe1=value1 -l labe2=value2" results in a selection of resources with "label2=value2"  (the second "-l" argument overwrites the first one) and this is "working as designed"

so if someone specifies multiple labels, concatenating them with commas is the only way to get the expected "and" selection behavior.

**Comment by gabemontero** [comment]
though it has been problematic independent of PR changes, trying [test]

I'll pull the change and at least validate it does not break existing behavior.

@tanskann - would it be at all possible for you to add some flavor of what you've been testing this change with to example/jenkins-image-sample.groovy?  If not I'll see about adding something later on.

**Comment by gabemontero** [comment]
@tanskann i've got a test in hand ... disregard my last request - thanks!

merging ....

**Pull request merged**
