### PR TITLE
update curl pod to conform to tighter pod security restrictions in 4.11

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
/label px-approved 

test in CI only

**Comment by gabemontero** [comment]
/label qe-approved

test in CI only

**Comment by gabemontero** [comment]
/label docs-approved

test in CI only

**Comment by gabemontero** [comment]
bump @coreydaley 

maybe got lost in the shuffle yesterday

**Comment by coreydaley** [comment]
/lgtm
Yep, I think I was waiting for the tests to pass and forgot to come back to it.

**Pull request merged**
