### PR TITLE
enable regression testing for v1.0.5 changes

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience @jupierce @stevekuznetsov this is step 4) from https://github.com/openshift/jenkins-client-plugin/pull/107

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
origin prereqs step failed ... no more hosts ... will retest again when that clears up

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
@sdodson .... fyi - @stevekuznetsov told me that @deads2k hit this origin prereqs issue too in the test job here ....
`"msg": "To install a containerized Origin release,\nyou must set openshift_release or openshift_image_tag in your inventory to\nspecify which version of the OpenShift component images to use.\n(Suggestion: add openshift_release=\"x.y\" to inventory.)"`

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
ran this updated test case manually as a work around for the ci infra issue noted above.

merging via button

**Comment by gabemontero** [comment]
cool the ci flake got fixed ... the tests are running / passing again ^^

**Comment by sdodson** [comment]
@gabemontero https://github.com/openshift/aos-cd-jobs/pull/988 fixed the problem

**Comment by gabemontero** [comment]
thanks @sdodson !

**Pull request merged**
