### PR TITLE
generic safety check on currentContext

### PR DESCRIPTION
**Pull request by gabemontero**
@jupierce @stevekuznetsov - update per last few exchanges in https://github.com/openshift/jenkins-client-plugin/issues/104

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by stevekuznetsov** [comment]
So the error message is now `"proper use of openshift.withCluster() could not be detected"`?

It might be a bit clearer to and end user to say something to make it clear that it is improper to execute whatever thing the user is trying to do outside of a `withCluster()` call -- it's not immediately clear what a "proper" use is. Or maybe that's too specific? As a dumb user I just want to hear "hey, dumbo, you typed `openshift.selector()` outside of an `openshift.withCluster()` block. That's illegal."

**Comment by gabemontero** [comment]
sure thing message updated

**Comment by stevekuznetsov** [comment]
Thanks @gabemontero

**Comment by gabemontero** [comment]
On Tue, Jan 9, 2018 at 12:33 PM Steve Kuznetsov <notifications@github.com>
wrote:

> Thanks @gabemontero <https://github.com/gabemontero>
>
np thanks for the prodding

**Pull request merged**
