### PR TITLE
add test for selector.rollout().status(-w)

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
@bparees - with both this PR and https://github.com/openshift/jenkins-client-plugin/pull/44 I've noticed odd failures which make me think something environmental like disk space is sabotaging the test.  There is an event related to the builder image not being available in this PR's run.  But nothing explicit like problems writing a file, etc. that I at least have noticed before.

The overnight ext test runs seem to have been failing with setup type issues as well.

Anyway, you have a sec to take a peek, give a second opinion / sanity check before we either chalk it up to that or bring in overloaded ci infrastructure folks?

**Comment by bparees** [comment]
can we dump the output of a "df" and "docker info" as part of the test job before tearing down the ec2 instance?  that would be the best way to know if we ran of out disk, or docker storage.

this is what stuck out to me, but maybe you understand it?
```
[Pipeline] echo
Caught: hudson.AbortException: watch terminated with an error: 1
[Pipeline] End of Pipeline
ERROR: watch terminated with an error: 1
Finished: FAILURE
```

seemingly correlated to:
```
INFO: starting polling build job/extended-test-jenkins-pipeline-3m3s9-l5vhq-sample-pipeline-openshift-client-plugin/1/
Jun 27, 2017 8:17:19 PM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
WARNING: already completed CpsStepContext[110:_OcWatch]:Owner[extended-test-jenkins-pipeline-3m3s9-l5vhq-sample-pipeline-openshift-client-plugin/1:extended-test-jenkins-pipeline-3m3s9-l5vhq-sample-pipeline-openshift-client-plugin #1]
java.lang.IllegalStateException: delivered here
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.completed(CpsStepContext.java:352)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.onSuccess(CpsStepContext.java:332)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Jun 27, 2017 8:17:20 PM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: new success: null
Jun 27, 2017 8:17:20 PM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: previously delivered here
java.lang.Throwable
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.completed(CpsStepContext.java:340)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.onFailure(CpsStepContext.java:328)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:199)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:77)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Jun 27, 2017 8:17:20 PM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: earlier failure
hudson.AbortException: watch terminated with an error: 1
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:188)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:77)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Jun 27, 2017 8:17:20 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: extended-test-jenkins-pipeline-3m3s9-l5vhq-sample-pipeline-openshift-client-plugin #1 completed: FAILURE
```

**Comment by bparees** [comment]
(to be clear i was looking at this job which is the last run on this PR: https://ci.openshift.redhat.com/jenkins/job/test-openshift-client-plugin/36/consoleFull)

**Comment by gabemontero** [comment]
Yeah pretty positive those stack traces in the jenkins sys log are the aftermath of our test timing out / failing.

Adding some disk space analysis to the pipeline extended test is a good ideal.  And we should still have those diagnostics from back when we had the xfs quota issue.  I'll construct a pull in origin for that.

Given the nature of these failures, as well as the success of running locally, I do plan on merging this PR and 44 today, and then proceed to cutting a new version and updating the post 3.6 jenkins branch.  But I'll wait a bit in case you want to chime in with an objection.

**Comment by bparees** [comment]
> But I'll wait a bit in case you want to chime in with an objection.

no that's fine, especially since this plugin is still "experimental" for 3.6.

**Comment by gabemontero** [comment]
ok cool thanks

**Pull request merged**
