### PR TITLE
need getters for raw step; readme fixes

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-client-plugin/issues/70

@openshift/sig-developer-experience fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
I'll update this pull as we progress through the process of cutting a new version of the plugin in the jenkins update center and updating the openshift jenkins centos image

@bparees - feelings on squeezing this into 3.7?  I don't have strong feelings either way.

**Comment by bparees** [comment]
> @bparees - feelings on squeezing this into 3.7? I don't have strong feelings either way.

seems safe enough, i say go for it if you can do it today.

**Comment by gabemontero** [comment]
fyi ... due to some release hiccups on my part ... the commit from this PR was replaced by commit f811abd439f69a972f99e3f03362edb2561b9321

**Pull request merged**
