### PR TITLE
OCPBUGS-7636,OCPBUGS-6023,OCPBUGS-6019,OCPBUGS-6020,OCPBUGS-2021,OCPBUGS-2022: Force bumps xstream (transitive dependency) version to 1.4.20

### PR DESCRIPTION
**Pull request by apoorvajagtap**
As per current `mvn dependency:tree`, the  `jenkins-core` is dependent on xstream-v1.4.16.
> [INFO] +- org.jenkins-ci.main:jenkins-core:jar:2.289.1:provided
> ...
> [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.16:provided
> [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.1:provided

Bumping the xstream version to 1.4.20. (ref: https://github.com/x-stream/xstream/security/advisories/GHSA-j563-grx4-pjpv).

### CODE REVIEW

**Comment by coreydaley** [comment]
I think it would be better to bump jenkins https://github.com/openshift/jenkins-client-plugin/blob/master/pom.xml#L21 instead of trying to bump the dependency directly.

**Comment by coreydaley** [comment]
You need to update https://github.com/openshift/jenkins-client-plugin/blob/master/pom.xml#L8 to `4.32` and https://github.com/openshift/jenkins-client-plugin/blob/master/Dockerfile#L8 to `RUN mvn clean package`

**Comment by coreydaley** [comment]
I had to make similar updates to jenkins-sync-plugin (via https://github.com/openshift/jenkins-sync-plugin/pull/434/files) when I updated the Jenkins version.

**Comment by coreydaley** [comment]
The test is using an older version of the Jenkins image to run (whatever the samples operator is currently set up to use). So once we have the newest jenkins images built and released, then we should be able to update the cluster samples operator, which should fix this error about a higher version of jenkins needed, so this pull request/cve fix may have to wait a sprint.

```
2023-04-03 19:22:40 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin OpenShift Client Jenkins Plugin v1.0.39-SNAPSHOT (private-4984efd4-root) (openshift-client)
java.io.IOException: Failed to load: OpenShift Client Jenkins Plugin (openshift-client 1.0.39-SNAPSHOT (private-4984efd4-root))
 - Update required: Pipeline: Groovy (workflow-cps 3536.vb_8a_6628079d5) to be updated to 3565.v4b_d9b_8c29a_b_3 or higher
 - Jenkins (2.387.1) or higher required
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:994)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:543)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1161)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:222)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:121)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by coreydaley** [comment]
/hold
until we release a new version of the jenkins image and update the samples operator

**Comment by coreydaley** [comment]
@apoorvajagtap Can you please re-evaluate if this is still needed?

**Comment by coreydaley** [comment]
@apoorvajagtap Can you please re-evaluate if this is still needed?

**Comment by apoorvajagtap** [comment]
Fixed with the latest releases.

**Pull request closed without merging**
