### PR TITLE
added rsync

### PR DESCRIPTION
**Pull request by ramato-procon**
Added rsync functionallity to transfer files from/to pods.

### CODE REVIEW

**Comment by ramato-procon** [comment]
[test]

**Comment by ramato-procon** [comment]
@bparees Can you please review my PR?
I also added the rsh command from https://github.com/openshift/jenkins-client-plugin/pull/81
to the help page.

**Comment by bparees** [comment]
@coreydaley please take a first pass. @gabemontero i'm ok w/ this if you are.

**Comment by gabemontero** [comment]
I'm cool with it.

Opened https://github.com/openshift/jenkins-client-plugin/issues/93 to track adding use of rsync to our automated test suite once we cut new versions of the plugin/image.

**Comment by gabemontero** [comment]
I'll give @coreydaley a chance to chime in though before merging.

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
