### PR TITLE
protect from presence of ad hoc .kube/config files

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-client-plugin/issues/89

@openshift/sig-developer-experience fyi

@elconas - if you think you would have the cycles, I can attach an hpi file with this change for you to try prior to merging / cutting a new version of the plugin - thanks

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
there was a problem downloading a maven dependency during the build stage of the pr test

i'll give upstream a bit to settle, and re-kick

**Comment by bparees** [comment]
I have some concerns about removing a feature which is that users can set KUBECONFIG to point to the config they want to use.

i'd also like to better understand where the existing KUBECONFIG env var is coming from before we go stomping it.

I don't think this problem is so urgent that we need to push a fix in w/o considering the other items you mentioned in the issue.

**Comment by gabemontero** [comment]
yep, fair enough - as much as anything, I wanted to generate the discussion

I also realized, though didn't get around to addressing, that the plugin change could do things like 
a) see if some likely locations for `.kube/config` like JENKINS_HOME or WORKSPACE existed before overriding KUBECONFIG
b) see if the new default is not in place for KUBECONFIG prior to running

And I realized a few moments ago
c) and that the change in the jenkins image to base off of the openshift/origin image was in the 3.7 timeframe; so that explains why @elconas was not seeing `KUBECONFIG` set and had to explicitly set it ... in theory, if he moves to a 3.7 image, it will be set to the default from the openshift/origin anyway, and bypass the local `.kube/config` file he had.

**Comment by gabemontero** [comment]
I'm going to close this pull and the associated issue out based on my point c) from https://github.com/openshift/jenkins-client-plugin/pull/90#issuecomment-348304477 about the 3.7 image change,
along with the other concerns noted

**Pull request closed without merging**
