### PR TITLE
update pr tester readme with new invocation cmd for ext test

### PR DESCRIPTION
**Pull request by gabemontero**
@dobbymoodge @stevekuznetsov @bparees fyi going to actually attempt a mrg of this change with the new aos-cd-jobs / ci-config / origin-ci-tool infra

### CODE REVIEW

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
So the merge job was found and started executing, but did not last long.  It fails on the first sh/cmd step in the build job:

```
+ approve.sh jenkins-client-plugin master none
[ERROR] No approval criteria are configured for 'master' branch of 'jenkins-client-plugin' repo.
```

@dobbymoodge - any idea how those approval criteria are configured?  As a point of comparison, I see the same call to approve.sh as the first step in other merge_pull_request_* jobs.

thanks

**Comment by dobbymoodge** [comment]
@gabemontero Here's what I could find about setting up the approvers: <https://github.com/openshift/aos-cd-jobs#pull-request-approvers-under-approvers>. I think it's something @stevekuznetsov or I would need to do, though I've never touched it before.

**Comment by gabemontero** [comment]
Yeah, and in relation to what you noted, it looks like https://github.com/openshift/aos-cd-jobs#configuring-branch-status needs to happen.

I don't have an login access to `ci.dev.openshift`, only to `ci.openshift`, so I can't run that job.  So yes, please see about running it, where hopefully you can specify precisely and only the 4 plugin repos (jenkins-plugin, jenkins-client-plugin, jenkins-sync-plugin, and jenkins-openshift-login-plugin).

**Comment by dobbymoodge** [comment]
@gabemontero pinged @jupierce about this, I think he might be in charge of this process?

**Comment by stevekuznetsov** [comment]
This is super downstream of releases and the version of this plugin gets gated by the version of the Jenkins image we're using, so we could probably just keep this repo open at all times.

**Comment by stevekuznetsov** [comment]
Err, super upstream.

**Comment by gabemontero** [comment]
Yes keeping it open is my preference given the "super upstream-ness" to paraphrase @stevekuznetsov 

There are several layers of control on top of this:
1) merging the commit to jenkinsci and cutting an image
2) adding the new plugin version to our jenkins centos image (jenkins repo is under control of the various severities / stages)
3) crafting a rpm and updating the rhel image

**Comment by jupierce** [comment]
The branch should presently be open.

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
Yeah, same problem.  `approve.sh` unhappy.

@jupierce - from your previous comment, did you mean that you ran https://github.com/openshift/aos-cd-jobs#configuring-branch-status for jenkins-client-plugin ?

thanks

**Comment by jupierce** [comment]
@gabemontero Sorry, I misread which repo this was on my phone last night. I will make a new approver for jenkins-client-plugin now.

**Comment by jupierce** [comment]
[merge]

**Comment by gabemontero** [comment]
great - thanks @jupierce !

I've also created jobs for jenkins-plugin, jenkins-sync-plugin, and jenkins-openshift-login-plugin.  Can you create approvers for those as well?

**Comment by jupierce** [comment]
@gabemontero Done!

**Comment by gabemontero** [comment]
thanks @jupierce ! .. will give them a try in a bit

**Pull request merged**
