### PR TITLE
Bug 2054816: Allow OpenShiftTokenCredentials from sync-plugin to be used as cluster creds

### PR DESCRIPTION
**Pull request by akram**
Fixes https://github.com/openshift/jenkins-sync-plugin/issues/414

After removing the dependency between sync plugin and client plugin, credentials synced by the sync plugin were not usable.
This fix enables them as selectable values for the client plugin

### CODE REVIEW

**Comment by gabemontero** [comment]
@akram I'm going to associated the bz https://bugzilla.redhat.com/show_bug.cgi?id=2054816 with this PR ... we'll just need to move it back to post after this merges so that @jitendar-singh does not test this until we've bumped the plugin and updated the image.

**Comment by gabemontero** [comment]
/retitle Bug 2054816: Allow OpenShiftTokenCredentials from sync-plugin to be used as cluster creds

**Comment by akram** [comment]
@gabemontero I will go for cutting a version

**Comment by gabemontero** [comment]
yes will do @akram

**Comment by gabemontero** [comment]
https://github.com/openshift/jenkins-client-plugin/pull/379 is up @akram 

interestingly I still do not see 1.36 up at the jenkins update center yet

**Pull request merged**
