### PR TITLE
pr-testing-test

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
@stevekuznetsov @droslean @petr-muller hey ... with https://github.com/openshift/release/pull/3177 merging, I'm seeing all the super-cool `ci/prow/*` jobs in this repo's PR as I expected.

But I'm also seeing a ref to the old jenkins based / aos-cd-job / etc. `ci/openshift-jenkins`

I just did a ` find . -name "*" -exec grep -s -H openshift-jenkins {} \;` in the openshift/release repo and am not seeing any references there that could have bearing

Do I just need to wait for some background processing to occur to delete the `ci/openshift-jenkins` ref?
Do I need to remove the aos-cd-jobs content to delete the `ci/openshift-jenkins` ref?
Or is some manual processing from one of y'all needed?

thanks

**Comment by stevekuznetsov** [comment]
Where are you seeing those?

**Comment by gabemontero** [comment]
in the status section when viewing the PR from a browser
screenshot-4-steve

**Comment by gabemontero** [comment]
and now it has disappeared ... you do something @stevekuznetsov or did some expected background job fire?

**Comment by gabemontero** [comment]
glad I took that screen shot :-)

**Pull request closed without merging**
